---
- hosts: BASTION_AWS
  become: yes

  gather_facts: no

  vars:
    carriere:
      - alpha
      - beta
  tasks:
    - name: collecte de mes vars
      include_vars: ansible/group_vars/web_vars.yml


    - debug:
        msg: |
          legumes > 4 : {{ legumes_culinaires|selectattr('qte', 'greaterthan', 4)|map(attribute='name')|join(',') }}

    - set_fact:
        greatest_legumes: "{{ greatest_legumes|default([]) + [item] }}"
      with_items: "{{ legumes_culinaires }}"
      when: "{{ item.qte > 4 }}"

    - debug:
        var: greatest_legumes
    - apt:
        name: apache2

    - service:
        name: apache2
        state: started

    - debug:
        var=carriere

    - template:
        src: index.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0600'

