---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
    servers:
      - key: "amaury_aws"
        type: "t2.micro"
        image: "ami-e079f893"
        subnet: "subnet-bfa8d6e7"
        count_tags:
          Name: database
          dbtype: postgres
        instance_tags:
          Name: database
          dbtype: postgres
        security_group_name: "sg_ssh_http"
    uuid: "{{ servers[0]|string|to_uuid }}"
    str_uuid: "{{ servers[0]|string }}"

  tasks:
    - debug:
        msg: "compare to {{ uuid }}"

    - debug:
        msg: "compare to {{ str_uuid }}"

    - ec2:
        key_name: "{{ item.key }}"
        instance_type: "{{ item.type }}"
        image: "{{ item.image }}"
        wait: yes
        group: "{{ item.security_group_name }}"
        instance_tags: "{{ item.instance_tags }}"
        count_tag: "{{ item.count_tags }}"
        exact_count: "{{ item.count }}"
        vpc_subnet_id: "{{ item.subnet }}"
        id: "{{ item|string|to_uuid }}"
        assign_public_ip: yes
      with_items: "{{ servers }}"


