---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
    exo_name: "exo_02-GCP-infra"

  pre_tasks:
    - debug:
        msg: "Checking initial conditions."

    - fail:
        msg: >-
          Host variable {{ item }} for localhost is required.
          Please define it in 'ansible/host_vars/localhost.yml'.
      when: "{{ hostvars['localhost'][item] is not defined }}"
      with_items:
        - "admin_key"
        - "aws_padawans"

    - debug:
        msg: "Seems to be matching. Going on."

  tasks:
    - name: Applying Terraform (may take several minutes)
      shell: >-
        terraform apply
      args:
        chdir: "{{ playbook_dir }}/../terraform/{{ exo_name }}"
      register: tf_apply_raw
      changed_when: not (tf_apply_raw.stdout|search('0 added, 0 changed, 0 destroyed'))
      tags:
        - apply

    - name: Extracting terraform output vars
      shell: >-
        terraform output bastion
      args:
        chdir: "{{ playbook_dir }}/../terraform/{{ exo_name }}"
      register: tf_bastion_raw

    - set_fact:
        bastion_ip: "{{ tf_bastion_raw.stdout }}"

    - name: Generating ssh.cfg
      template:
        src="templates/ssh.cfg.j2"
        dest="{{ playbook_dir }}/../ssh.cfg"

    - name: Generating host inventory
      template:
        src="templates/inventory_02.j2"
        dest="{{ playbook_dir }}/inventories/training-02.inventory"

    - name: Adding default host inventory to ansible.cfg
      lineinfile:
        dest: "{{ playbook_dir }}/../ansible.cfg"
        line: "inventory = ./ansible/inventories/training.inventory"
        state: present
        insertafter: '^\[defaults\]$'

    - name: Adding ssh options to ansible.cfg
      blockinfile:
        dest: "{{ playbook_dir }}/../ansible.cfg"
        state: present
        block: |-
          [ssh_connection]
          pipelining=True
          ssh_args="-F ssh.cfg"
