---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
    exo_name: "exo_02-AWS-infra"
    tf_state_path: "{{ playbook_dir }}/../terraform/{{ exo_name }}/terraform.tfstate"

  pre_tasks:
    - debug:
        msg: "Checking initial conditions."

    - fail:
        msg: "Environment variable {{ item }} is required."
      when: "{{ lookup('env', item) == '' }}"
      with_items:
        - "AWS_DEFAULT_REGION"
        - "AWS_SECRET_ACCESS_KEY"
        - "AWS_ACCESS_KEY_ID"

    - fail:
        msg: >-
          Host variable {{ item }} for localhost is required.
          Please define it in 'ansible/host_vars/localhost.yml'.
      when: "{{ hostvars['localhost'][item] is not defined }}"
      with_items:
        - "admin_key"
        - "aws_padawans"

    - debug:
        msg: "Seems to be matching. Going on."

  tasks:
    - name: Applying Terraform (may take several minutes)
      shell: >-
        terraform apply
      args:
        chdir: "{{ playbook_dir }}/../terraform/{{ exo_name }}"
      register: tf_apply_raw
      changed_when: not (tf_apply_raw.stdout|search('0 added, 0 changed, 0 destroyed'))
      tags:
        - apply

    - set_fact:
        tf_state: "{{ lookup('file', tf_state_path)|from_json }}"

    - name: Extract values for next steps
      debug:
        msg:
          - "#######################################"
          - "subnet_id to deploy to: {{ tf_state.modules[0]['resources']['aws_subnet.public_subnet']['primary']['id'] }}"
          - "#######################################"
