---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
    server_count: 0
    subnet_id: "subnet-0f750d57"
    servers:
      - key: "amaury_aws"
        type: "t2.micro"
        image: "ami-e079f893"
        subnet: "{{ subnet_id }}"
        count: "{{ server_count }}"
        count_tags:
          Name: database
          dbtype: postgres
        instance_tags:
          Name: database
          dbtype: postgres
        security_group_name: "sg_ssh_http"

  tasks:
    - ec2:
        key_name: "{{ item.key }}"
        instance_type: "{{ item.type }}"
        image: "{{ item.image }}"
        wait: yes
        group: "{{ item.security_group_name }}"
        instance_tags: "{{ item.instance_tags }}"
        count_tag: "{{ item.count_tags }}"
        exact_count: "{{ item.count }}"
        vpc_subnet_id: "{{ item.subnet }}"
        assign_public_ip: yes
      with_items: "{{ servers }}"
      register: "ec2_instances_launch"


    - set_fact:
        ec2_hostnames: "{{ ec2_instances_launch.results[0].instances|map(attribute='public_ip')|list }}"
        ec2_ids: "{{ ec2_instances_launch.results[0].instances|map(attribute='id')|list }}"
      when: "{{ ec2_instances_launch|changed }}"

    - name: Generating host inventory
      template:
        src: "templates/inventory_02.j2"
        dest: "{{ playbook_dir }}/inventories/training-02.inventory"
      when: "{{ ec2_instances_launch|changed }}"

    - name: Adding default host inventory to ansible.cfg
      lineinfile:
        dest: "{{ playbook_dir }}/../ansible.cfg"
        line: "inventory = ./ansible/inventories/training-02.inventory"
        state: present
        insertafter: '^\[defaults\]$'

    - ec2_elb_lb:
        name: "training"
        scheme: internal
        state: present
        instance_ids: "{{ ec2_ids }}"
        purge_instance_ids: true
        subnets:
          - "{{ subnet_id }}"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
      register: elb_create
      when: "{{ ec2_instances_launch|changed and server_count|int > 0 }}"
