---
- hosts: localhost
  become: no
  gather_facts: no

  vars_prompt:
    - name: "confirmation"
      prompt: "If you really want to destroy this lab, please enter 'force'"
      private: no

  pre_tasks:
    - fail:
        msg: >-
          You are not sure. Next time, use the 'force' Luke.
      when: "{{ confirmation != 'force' }}"

  tasks:
    - include: "inc/undeploy_exo.yml"
      vars:
        exo_name: "exo_02-GCP-infra"