---
- name: Compute Engine Instance Examples
  hosts: localhost
  vars:
    service_account_email: "417819296333-compute@developer.gserviceaccount.com"
    credentials_file: "credentials.json"
    project_id: "pelagic-pager-155923"
    ma_zone: "europe-west1-b"
    mes_instances: 
      - apache-1
      - apache-2

  tasks:
    - name: create multiple instances
      # Basic provisioning example.  Create multiple Debian 8 instances in the
      # us-central1-a Zone of n1-standard-1 machine type.
      gce:
        instance_names: "{{ mes_instances | join(',') }}"
        zone: "{{ ma_zone }}"
        machine_type: f1-micro
        image: debian-8
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata : '{ "startup-script" : "apt-get update" }'
      register: gce

    - name: Save host data
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances_ips
      with_items: "{{ gce.instance_data }}"

    - name: Wait for SSH for instances
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 30
      with_items: "{{ gce.instance_data }}"

#    - name: Configure Hosts
#      hosts: gce_instances_ips
#      become: yes
#      become_method: sudo
#      roles:
#        - my-role-one
#        - my-role-two
#      tags:
#        - config

    - name: delete test-instances
      # Basic termination of instance.
      gce:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        instance_names: "{{ item }}"
        zone: "{{ ma_zone }}"
        state: absent
      with_items: "{{ mes_instances }}"

      tags:
        - delete
