---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
    servers:
      - key: "amaury_aws"
        type: "t2.micro"
        image: "ami-e079f893"
        subnet: "subnet-209de378"
        instance_tags:
          Name: Idem
          Role: bastion
        security_group_name: "sg_ssh_http"
    uuid: "{{ servers[0]|string|to_uuid }}"
    str_uuid: "{{ servers[0]|string }}"

  tasks:
    - debug:
        msg: "compare to {{ uuid }}"

    - debug:
        msg: "compare to {{ str_uuid }}"

    - ec2:
        key_name: "{{ item.key }}"
        instance_type: "{{ item.type }}"
        image: "{{ item.image }}"
        wait: yes
        group: "{{ item.security_group_name }}"
        instance_tags: "{{ item.instance_tags }}"
        vpc_subnet_id: "{{ item.subnet }}"
        id: "{{ item|string|to_uuid }}"
        instance_ids:
          - i-0decbe827b125af17
        state: absent
        assign_public_ip: yes
      register: servers_res
      with_items: "{{ servers }}"

    - debug:
        var: servers_res
